export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const GET_USER_INFO = 'GET_USER_INFO';

export const GET_EQUIPMENT = 'GET_EQUIPMENT';

export const GET_STAKEHOLDERS_REQUESTS = 'GET_STAKEHOLDERS_REQUESTS';
export const STAKEHOLDER_CREATE = 'STAKEHOLDER_CREATE';

export const CREATE_CHAT = 'CREATE_CHAT';
export const SHOW_CHAT_LIST = 'SHOW_CHAT_LIST';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const SHOW_ALL_MESSAGE = 'SHOW_ALL_MESSAGE';
export const GET_USER_LIST = 'GET_USER_LIST';

export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS';
export const GET_ALL_SPRINTS_BY_PROJECT = 'GET_ALL_SPRINTS_BY_PROJECT';
export const GET_ALL_ISSUES_BY_SPRINT = 'GET_ALL_ISSUES_BY_SPRINT';

export const GET_ALL_ISSUES_BY_PROJECT = 'GET_ALL_ISSUES_BY_PROJECT';

export const GET_MY_TEAMS = 'GET_MY_TEAMS';
export const GET_ALL_LABORATORY = 'GET_ALL_LABORATORY';

export const GET_ALL_COMPETENCES = 'GET_ALL_COMPETENCES';